-- =====================================================================
-- Nouf-ex — Seed data (noufex_db)
-- =====================================================================
-- Idempotent: every INSERT uses ON CONFLICT DO NOTHING (or DO UPDATE
-- for the wallet). Re-running db-setup on an existing DB is safe.
--
-- Demo credentials (all use scrypt password hashing):
--   admin@noufex.com               / admin123     (role=admin)
--   ahmed@gmail.com                / customer123  (role=customer)
--   sara@gmail.com                 / customer123  (role=customer)
--   omar@gmail.com                 / customer123  (role=customer)
--   fatima@spice-yemen.com         / merchant123  (role=merchant)
--   hassan@dates-yemen.com         / merchant123  (role=merchant)
--   mohammed@handicrafts-yemen.com / merchant123  (role=merchant)
--   khalid@electronics-yemen.com   / merchant123  (role=merchant)
--   noor@perfume-yemen.com         / merchant123  (role=merchant)
--   layla@mokha-coffee.com         / merchant123  (role=merchant)
--
-- The scrypt hashes below were generated by scripts/gen-seed-hashes.cjs.
-- DO NOT regenerate for these users without also re-running that script
-- with the same plaintexts.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- USERS — explicit IDs for FK stability
-- ---------------------------------------------------------------------
INSERT INTO users (id, email, password_hash, full_name, phone, role, status,
                   is_verified, email_verified, phone_verified, avatar,
                   preferred_language, gender)
OVERRIDING SYSTEM VALUE
VALUES
(1,  'admin@noufex.com',
  'scrypt$OnSXEANSpcXJkTYryVu2Qw==$fb2h3uxf8jVS3rNUThwMSeC89WpCKl6wFcfiKRl3suUFbDh5lN3kTkqPoUuntI/54I5CJ7J/4zbeo5Qglx8mTg==',
  'System Administrator', '+967711111111', 'admin', 'active',
  TRUE, TRUE, TRUE, NULL, 'ar', NULL),
(2,  'ahmed@gmail.com',
  'scrypt$69zEFtT9PMjmDlFrA31t1w==$kkWH6q3VvawE03v7Ls+eqhgFPYERf70SbxxVCp6d1cxno+5qDdqRtOdOg1+s0awXdP0kwJWQcyjXEerfh1f7sg==',
  'Ahmed Al-Maqtari', '+967712345671', 'customer', 'active',
  TRUE, TRUE, TRUE, NULL, 'ar', 'male'),
(3,  'sara@gmail.com',
  'scrypt$Ffq03xyB6kIPtfM97Bl45A==$4V4FoGQPq2qCtqjVZvTrvI2EGcgvXlWj/Gr/8IX4/s1jO99rb6G6BTobkfc0piSIcuxoXuxjuCZZ4t8ViUTXsQ==',
  'Sara Al-Hadhrami', '+967712345672', 'customer', 'active',
  TRUE, TRUE, TRUE, NULL, 'ar', 'female'),
(4,  'omar@gmail.com',
  'scrypt$PH6pMAHXPST2bNUQ/DyvOw==$AaXDgr2fCP397LuqaRSkx38ov3f4uWNGcovShH9+JSuQrZoCLhnUh3KuE9hjL535n8LENvcevq8azaf2hWJ/Ig==',
  'Omar Al-Amiri', '+967712345673', 'customer', 'active',
  FALSE, FALSE, FALSE, NULL, 'ar', 'male'),
(5,  'fatima@spice-yemen.com',
  'scrypt$s1Z7B+i1yiaJWlmq9+93MA==$gHS2qArujTbgZmTyfiJN8iRbD52MXBu7Q6fodUraz0Fop/5eSDfcUKttNKwWpmJ6IThuRBuLjMXM6wZWXSBXpQ==',
  'Fatima Al-Sharabi', '+967712345674', 'merchant', 'active',
  TRUE, TRUE, TRUE, NULL, 'ar', 'female'),
(6,  'hassan@dates-yemen.com',
  'scrypt$Avl2w1gUqPMJuqlHO22DvA==$HK3bhnv2BTpDuVnyQqDuZJCS6Xl3bJPilx8PiHhOBTU847R2GRlu2G6LDrHU5Cn7zPSrAQPGd2tD91qUKFLcNQ==',
  'Hassan Al-Mahdi', '+967712345675', 'merchant', 'active',
  TRUE, TRUE, TRUE, NULL, 'ar', 'male'),
(7,  'mohammed@handicrafts-yemen.com',
  'scrypt$xbjupiWOirt8unePsFnUcg==$KE/Tqb+OzqhekoH3r63FyDS//+KipWHUEh7NyCxex5ZrICqC52/mcKqhLC/qivUgkEBPnIOI5NG/jo6UxBzwMw==',
  'Mohammed Bani Hushaish', '+967712345676', 'merchant', 'active',
  TRUE, TRUE, TRUE, NULL, 'ar', 'male'),
(8,  'khalid@electronics-yemen.com',
  'scrypt$jsxYGtdEZaclhyAiXW+aSQ==$Q11qCszs74Xm4WVPeZHHpYl6V1eYDKofMm18eBsxWE0HRG01gg0Yr/BLp5PHRwL4bbR159cwxiV1fnUJUTNP6w==',
  'Khalid Al-Sharjabi', '+967712345677', 'merchant', 'active',
  TRUE, TRUE, TRUE, NULL, 'ar', 'male'),
(9,  'noor@perfume-yemen.com',
  'scrypt$jS30qMRM6PJh+wS0lxz2zw==$79MVwe3lISndUcNBMQsCY95Kgg39pKMyiBh3SDKPYPo6YueYdlHy31vEsVUcm6YcE0F/6H2A43EimIhuyeLZeg==',
  'Noor Al-Khazen', '+967712345678', 'merchant', 'active',
  TRUE, TRUE, TRUE, NULL, 'ar', 'female'),
(10, 'layla@mokha-coffee.com',
  'scrypt$4+NUHh9EY7TlQjfvtpxIGw==$E48o2DOf7Yqc1QFkRJJFzEM3efKn+CjMd/fmhzZT3bkPTE2rIMrVcopScYomUZjJeKaXxdueKA+mHCYnvvMFEQ==',
  'Layla Al-Maqtari', '+967712345679', 'merchant', 'active',
  TRUE, TRUE, TRUE, NULL, 'ar', 'female')
ON CONFLICT (id) DO NOTHING;
-- Reset sequence past the explicit IDs.
SELECT setval(pg_get_serial_sequence('users','id'), GREATEST((SELECT MAX(id) FROM users), 1));

-- ---------------------------------------------------------------------
-- CATEGORIES
-- ---------------------------------------------------------------------
INSERT INTO categories (id, parent_id, name_ar, name_en, name_zh, slug,
                        icon, sort_order, is_active)
OVERRIDING SYSTEM VALUE
VALUES
(1,  NULL, 'إلكترونيات',    'Electronics',    '电子产品',    'electronics',    '📱', 1,  TRUE),
(2,  NULL, 'المواد الغذائية', 'Food & Beverages', '食品饮料', 'food-beverages', '🍯', 2,  TRUE),
(3,  NULL, 'الأزياء',         'Fashion',         '服装',       'fashion',        '👗', 3,  TRUE),
(4,  NULL, 'المنزل والمطبخ',  'Home & Kitchen',  '家居厨房',  'home-kitchen',   '🏠', 4,  TRUE),
(5,  NULL, 'الجمال والعناية', 'Beauty & Care',    '美容护理',  'beauty-care',    '💄', 5,  TRUE),
(6,  NULL, 'الحرف اليدوية',   'Handicrafts',      '手工艺品',  'handicrafts',    '🧶', 6,  TRUE),
(7,  NULL, 'السيارات',        'Automotive',       '汽车',       'automotive',     '🚗', 7,  TRUE),
(8,  1,    'هواتف',           'Phones',           '手机',       'phones',         '📞', 1,  TRUE),
(9,  1,    'أجهزة لوحية',     'Tablets',          '平板电脑',   'tablets',        '💻', 2,  TRUE),
(10, 1,    'سماعات',          'Headphones',       '耳机',       'headphones',     '🎧', 3,  TRUE),
(11, 2,    'عسل',             'Honey',            '蜂蜜',       'honey',          '🍯', 1,  TRUE),
(12, 2,    'قهوة',            'Coffee',           '咖啡',       'coffee',         '☕', 2,  TRUE),
(13, 2,    'تمور',            'Dates',            '椰枣',       'dates',          '🌴', 3,  TRUE),
(14, 3,    'رجالي',           'Men',              '男装',       'men',            '👔', 1,  TRUE),
(15, 3,    'نسائي',           'Women',            '女装',       'women',          '👗', 2,  TRUE),
(16, 6,    'سلال',            'Baskets',          '篮子',       'baskets',        '🧺', 1,  TRUE),
(17, 6,    'فضيات',           'Silverware',       '银器',       'silverware',     '🥈', 2,  TRUE),
(18, 5,    'عطور',            'Perfumes',         '香水',       'perfumes',       '🌹', 1,  TRUE)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('categories','id'), GREATEST((SELECT MAX(id) FROM categories), 1));

-- ---------------------------------------------------------------------
-- STORES — one per merchant
-- ---------------------------------------------------------------------
INSERT INTO stores (id, owner_id, store_name, store_name_en, store_name_zh,
                    slug, description, description_en, description_zh,
                    logo, banner, location, governorate,
                    trust_level, response_rate, on_time_delivery,
                    commission_rate, since_year, is_active, is_verified)
OVERRIDING SYSTEM VALUE
VALUES
(1, 5, 'بهارات اليمن',  'Yemen Spice House', '也门香料之家',
   'yemen-spice-house', 'بهارات يمنية أصيلة من قلب حضرموت', 'Authentic Yemeni spices from Hadramaut', '也门哈德拉毛正宗香料',
   '/stores/yemen-spice-logo.png', '/stores/yemen-spice-banner.jpg', 'المكلا', 'حضرموت',
   'diamond', 99.5, 98.7, 5, '2018', TRUE, TRUE),
(2, 5, 'عطور الملكة',   'Queen Perfumes',     '女王香水',
   'queen-perfumes', 'عطور شرقية فاخرة', 'Luxury oriental perfumes', '奢华东方香水',
   '/stores/queen-perfumes-logo.png', '/stores/queen-perfumes-banner.jpg', 'صنعاء', 'صنعاء',
   'golden', 97.8, 96.5, 6, '2020', TRUE, TRUE),
(3, 6, 'تمور الجوف',    'Jawf Dates',         '焦夫椰枣',
   'jawf-dates', 'تمور فاخرة من الجوف', 'Premium dates from Al-Jawf', '焦夫优质椰枣',
   '/stores/jawf-dates-logo.png', '/stores/jawf-dates-banner.jpg', 'الجوف', 'الجوف',
   'diamond', 98.9, 97.2, 5, '2017', TRUE, TRUE),
(4, 7, 'حرف يدوية يمنية', 'Yemen Handicrafts',  '也门手工艺品',
   'yemen-handicrafts', 'حرف يدوية تراثية أصيلة', 'Authentic traditional handicrafts', '正宗传统手工艺品',
   '/stores/yemen-handicrafts-logo.png', '/stores/yemen-handicrafts-banner.jpg', 'صنعاء', 'صنعاء',
   'golden', 96.3, 95.8, 7, '2019', TRUE, TRUE),
(5, 8, 'إلكترونيات اليمن', 'Yemen Electronics',  '也门电子产品',
   'yemen-electronics', 'كل ما تحتاجه من إلكترونيات', 'All your electronics needs', '您所有的电子产品需求',
   '/stores/yemen-electronics-logo.png', '/stores/yemen-electronics-banner.jpg', 'عدن', 'عدن',
   'verified', 95.2, 94.1, 6, '2021', TRUE, FALSE),
(6, 9, 'بخور وعطور',     'Incense & Perfumes',  '熏香和香水',
   'incense-perfumes', 'بخور عربي أصيل', 'Authentic Arabian incense', '正宗阿拉伯熏香',
   '/stores/incense-perfumes-logo.png', '/stores/incense-perfumes-banner.jpg', 'تعز', 'تعز',
   'verified', 94.7, 93.5, 7, '2020', TRUE, FALSE),
(7, 10, 'بن المخا',       'Mokha Coffee',       '摩卡咖啡',
   'mokha-coffee', 'بن يمني فاخر', 'Premium Yemeni coffee', '优质也门咖啡',
   '/stores/mokha-coffee-logo.png', '/stores/mokha-coffee-banner.jpg', 'المخا', 'تعز',
   'diamond', 99.1, 98.0, 5, '2016', TRUE, TRUE)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('stores','id'), GREATEST((SELECT MAX(id) FROM stores), 1));

-- ---------------------------------------------------------------------
-- PRODUCTS — 24 demo products across all stores/categories
-- ---------------------------------------------------------------------
INSERT INTO products (id, store_id, category_id, name_ar, name_en, name_zh,
                     description, description_en, description_zh,
                     price, original_price, currency, stock, moq, weight,
                     main_image, rating, review_count, sold_count, is_active,
                     is_featured, deal_discount)
OVERRIDING SYSTEM VALUE
VALUES
(1, 1, 11, 'عسل السدر اليمني الأصلي 500غ', 'Original Yemeni Sidr Honey 500g', '正宗也门西德里蜂蜜 500克',
   'عسل سدر يمني طبيعي 100% من جبال حضرموت، غني بالمعادن والفيتامينات',
   'Pure Yemeni Sidr honey from Hadramaut mountains, rich in minerals and vitamins',
   '也门哈德拉毛山纯天然西德里蜂蜜，富含矿物质和维生素',
   8500.00, 10000.00, 'YER', 50, 1, 500, '/products/p1-sidr-honey.jpg',
   4.9, 23, 156, TRUE, TRUE, 15),
(2, 1, 12, 'قهوة مخا اليمنية 250غ', 'Yemeni Mokha Coffee 250g', '也门摩卡咖啡 250克',
   'قهوة مخا الفاخرة المحمصة طازجة', 'Premium freshly roasted Mokha coffee', '优质新鲜烘焙摩卡咖啡',
   4500.00, NULL, 'YER', 100, 1, 250, '/products/p2-mokha-coffee.jpg',
   4.8, 45, 234, TRUE, TRUE, NULL),
(3, 1, 11, 'عسل المنجل البري 1 كغ', 'Wild Thyme Honey 1kg', '野生百里香蜂蜜 1公斤',
   'عسل منجل بري طبيعي 100%', 'Pure wild thyme honey', '纯野生百里香蜂蜜',
   15000.00, 18000.00, 'YER', 30, 1, 1000, '/products/p3-wild-thyme.jpg',
   5.0, 12, 89, TRUE, FALSE, 17),
(4, 3, 13, 'تمور مجدول فاخرة 1 كغ', 'Premium Majdool Dates 1kg', '优质马吉杜尔椰枣 1公斤',
   'تمور مجدول درجة أولى', 'First grade Majdool dates', '一级马吉杜尔椰枣',
   6500.00, NULL, 'YER', 200, 1, 1000, '/products/p4-majdool-dates.jpg',
   4.7, 34, 167, TRUE, TRUE, NULL),
(5, 3, 13, 'تمور عجوة المدينة 500غ', 'Ajwa Madinah Dates 500g', '麦地那艾吉瓦椰枣 500克',
   'تمور العجوة النبوية', 'Prophetic Ajwa dates', '圣训艾吉瓦椰枣',
   9500.00, 12000.00, 'YER', 75, 1, 500, '/products/p5-ajwa-dates.jpg',
   4.9, 28, 145, TRUE, TRUE, 21),
(6, 4, 16, 'سلة خوص يمنية يدوية', 'Handmade Yemeni Palm Basket', '手工也门棕榈篮',
   'سلة مصنوعة يدوياً من الخوص الطبيعي', 'Handmade basket from natural palm leaves', '天然棕榈叶手工编织篮子',
   3500.00, NULL, 'YER', 40, 1, 800, '/products/p6-palm-basket.jpg',
   4.6, 18, 92, TRUE, FALSE, NULL),
(7, 4, 17, 'طقم فضيات يمنية', 'Yemeni Silver Set', '也门银器套装',
   'طقم فضيات مصنوع يدوياً', 'Handcrafted silver set', '手工制作的银器套装',
   15000.00, 18000.00, 'YER', 15, 1, 600, '/products/p7-silver-set.jpg',
   4.8, 14, 56, TRUE, TRUE, 17),
(8, 4, 6, 'مبخرة خشبية محفورة', 'Carved Wooden Incense Burner', '手工雕刻木质香炉',
   'مبخرة محفورة يدوياً بخشب الأرز', 'Hand-carved cedar incense burner', '手工雕刻雪松香炉',
   4500.00, NULL, 'YER', 25, 1, 700, '/products/p8-wood-burner.jpg',
   4.7, 11, 67, TRUE, FALSE, NULL),
(9, 2, 18, 'عود كمبودي فاخر 100غ', 'Premium Cambodian Oud 100g', '优质柬埔寨沉香 100克',
   'عود طبيعي 100%', 'Pure natural oud', '纯天然沉香',
   25000.00, 30000.00, 'YER', 20, 1, 100, '/products/p9-cambodian-oud.jpg',
   4.9, 16, 89, TRUE, TRUE, 17),
(10, 2, 18, 'مسك أبيض نقي 50مل', 'Pure White Musk 50ml', '纯白麝香 50毫升',
   'مسك طبيعي بدون كحول', 'Natural alcohol-free musk', '天然无酒精麝香',
   5500.00, NULL, 'YER', 60, 1, 50, '/products/p10-white-musk.jpg',
   4.8, 22, 134, TRUE, FALSE, NULL),
(11, 2, 18, 'دهن العود الأصلي 25مل', 'Original Oud Oil 25ml', '正沉香油 25毫升',
   'دهن عود طبيعي نقي', 'Pure natural oud oil', '纯天然沉香油',
   18000.00, 22000.00, 'YER', 18, 1, 25, '/products/p11-oud-oil.jpg',
   5.0, 9, 45, TRUE, TRUE, 18),
(12, 5, 8, 'هاتف ذكي 6.5 إنش', 'Smartphone 6.5 inch', '智能手机 6.5英寸',
   'هاتف ذكي بشاشة كبيرة', 'Smartphone with large screen', '大屏智能手机',
   85000.00, 95000.00, 'YER', 30, 1, 250, '/products/p12-smartphone.jpg',
   4.5, 56, 234, TRUE, TRUE, 11),
(13, 5, 9, 'تابلت 10 إنش', 'Tablet 10 inch', '平板电脑 10英寸',
   'تابلت بدقة عالية', 'High-resolution tablet', '高分辨率平板电脑',
   65000.00, NULL, 'YER', 20, 1, 500, '/products/p13-tablet.jpg',
   4.4, 34, 178, TRUE, FALSE, NULL),
(14, 5, 10, 'سماعات بلوتوث لاسلكية', 'Wireless Bluetooth Headphones', '无线蓝牙耳机',
   'سماعات لاسلكية بجودة عالية', 'High-quality wireless headphones', '高品质无线耳机',
   12000.00, 15000.00, 'YER', 45, 1, 300, '/products/p14-headphones.jpg',
   4.6, 89, 356, TRUE, TRUE, 20),
(15, 5, 10, 'باور بانك 20000 mAh', 'Power Bank 20000 mAh', '充电宝 20000毫安',
   'بطارية محمولة عالية السعة', 'High-capacity portable battery', '大容量便携电池',
   8500.00, NULL, 'YER', 80, 1, 400, '/products/p15-powerbank.jpg',
   4.5, 45, 267, TRUE, TRUE, NULL),
(16, 6, 11, 'عسل أسود يمني 500غ', 'Yemeni Black Honey 500g', '也门黑蜂蜜 500克',
   'عسل أسود طبيعي', 'Natural black honey', '天然黑蜂蜜',
   7500.00, NULL, 'YER', 35, 1, 500, '/products/p16-black-honey.jpg',
   4.7, 18, 89, TRUE, FALSE, NULL),
(17, 6, 11, 'عسل المراعي 1 كغ', 'Meadow Honey 1kg', '草地蜂蜜 1公斤',
   'عسل من رحيق المراعي', 'Honey from meadow nectar', '草地花蜜蜂蜜',
   12000.00, 14000.00, 'YER', 25, 1, 1000, '/products/p17-meadow-honey.jpg',
   4.6, 14, 67, TRUE, TRUE, 14),
(18, 7, 12, 'قهوة عربية بالهيل 250غ', 'Arabic Cardamom Coffee 250g', '阿拉伯豆蔻咖啡 250克',
   'قهوة عربية فاخرة', 'Premium Arabic coffee', '优质阿拉伯咖啡',
   5500.00, NULL, 'YER', 60, 1, 250, '/products/p18-cardamom-coffee.jpg',
   4.8, 32, 145, TRUE, FALSE, NULL),
(19, 7, 12, 'قهوة تركية محمصة 500غ', 'Roasted Turkish Coffee 500g', '土耳其烘焙咖啡 500克',
   'قهوة تركية طازجة', 'Fresh Turkish coffee', '新鲜土耳其咖啡',
   7500.00, 9000.00, 'YER', 40, 1, 500, '/products/p19-turkish-coffee.jpg',
   4.7, 21, 98, TRUE, TRUE, 17),
(20, 7, 12, 'بن أرابيكا درجة أولى', 'Premium Arabica Beans', '优质阿拉比卡咖啡豆',
   'حبوب بن أرابيكا فاخرة', 'Premium Arabica coffee beans', '优质阿拉比卡咖啡豆',
   9500.00, NULL, 'YER', 50, 1, 1000, '/products/p20-arabica.jpg',
   4.9, 28, 167, TRUE, TRUE, NULL),
(21, 3, 13, 'تمور صقعي 500غ', 'Saqei Dates 500g', '萨基椰枣 500克',
   'تمور صقعي يمنية', 'Yemeni Saqei dates', '也门萨基椰枣',
   7500.00, NULL, 'YER', 80, 1, 500, '/products/p21-saqei-dates.jpg',
   4.5, 19, 89, TRUE, FALSE, NULL),
(22, 4, 17, 'خنجر يمني تقليدي', 'Traditional Yemeni Jambiya', '传统也门匕首',
   'خنجر يمني مصنوع يدوياً', 'Handmade traditional Yemeni dagger', '手工制作传统也门匕首',
   22000.00, 25000.00, 'YER', 8, 1, 400, '/products/p22-jambiya.jpg',
   4.9, 7, 34, TRUE, TRUE, 12),
(23, 2, 18, 'بخور بلدي فاخر 100غ', 'Premium Bakhour Badi 100g', '优质巴迪熏香 100克',
   'بخور بلدي طبيعي', 'Natural traditional incense', '天然传统熏香',
   3500.00, NULL, 'YER', 100, 1, 100, '/products/p23-bakhour.jpg',
   4.6, 25, 134, TRUE, FALSE, NULL),
(24, 7, 12, 'قهوة إسبريسو إيطالية 250غ', 'Italian Espresso 250g', '意大利浓缩咖啡 250克',
   'قهوة إسبريسو فاخرة', 'Premium espresso coffee', '优质浓缩咖啡',
   6500.00, NULL, 'YER', 35, 1, 250, '/products/p24-espresso.jpg',
   4.7, 17, 78, TRUE, TRUE, NULL)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('products','id'), GREATEST((SELECT MAX(id) FROM products), 1));

-- Update stores.products_count to match the seeded products
-- (The trg_products_refresh_store_count trigger will keep this in sync
-- afterwards, but we seed an explicit value here so reads return correct
-- numbers immediately after the seed runs.)
UPDATE stores SET products_count = sub.cnt
FROM (SELECT store_id, COUNT(*)::int AS cnt
        FROM products
       WHERE deleted_at IS NULL
       GROUP BY store_id) sub
WHERE stores.id = sub.store_id;

-- ---------------------------------------------------------------------
-- ADDRESSES — 2 per customer (1 default + 1 alternate)
-- ---------------------------------------------------------------------
INSERT INTO addresses (id, user_id, label, full_name, phone, city, governorate,
                       district, street, building, notes, is_default)
OVERRIDING SYSTEM VALUE
VALUES
(1, 2, 'المنزل', 'أحمد المقتاري', '+967712345671', 'صنعاء', 'صنعاء', 'الزبيري', 'شارع 30', 'عمارة النور', NULL, TRUE),
(2, 2, 'العمل',  'أحمد المقتاري', '+967712345671', 'صنعاء', 'صنعاء', 'التحرير', 'شارع 50', 'مبنى الشركة', NULL, FALSE),
(3, 3, 'المنزل', 'سارة الحضرمي',  '+967712345672', 'عدن',  'عدن',  'المعلا', 'شارع 10', 'فيلا الزهراء', NULL, TRUE),
(4, 3, 'الوالدة','سارة الحضرمي',  '+967712345672', 'عدن',  'عدن',  'خور مكسر', 'شارع 20', 'بيت الوالدة', NULL, FALSE),
(5, 4, 'المنزل', 'عمر العمري',    '+967712345673', 'تعز',  'تعز',  'وادي القاضي', 'شارع 15', 'عمارة الأمل', NULL, TRUE)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('addresses','id'), GREATEST((SELECT MAX(id) FROM addresses), 1));

-- ---------------------------------------------------------------------
-- SHIPPING_METHODS — global catalog
-- ---------------------------------------------------------------------
INSERT INTO shipping_methods (id, name_ar, name_en, name_zh, base_cost,
                              per_kg_cost, estimated_days, is_active, sort_order)
OVERRIDING SYSTEM VALUE
VALUES
(1, 'توصيل عادي',   'Standard Delivery', '标准配送', 500.00, 200.00, 3, TRUE, 1),
(2, 'توصيل سريع',   'Express Delivery',  '快速配送', 1000.00, 350.00, 1, TRUE, 2),
(3, 'توصيل في اليوم التالي', 'Next-Day Delivery', '次日达', 1500.00, 500.00, 1, TRUE, 3),
(4, 'استلام من المتجر', 'Store Pickup', '门店自提', 0.00, 0.00, 1, TRUE, 4)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('shipping_methods','id'), GREATEST((SELECT MAX(id) FROM shipping_methods), 1));

-- ---------------------------------------------------------------------
-- COUPONS — 4 demo coupons
-- ---------------------------------------------------------------------
INSERT INTO coupons (id, code, type, value, min_order_amount, max_discount,
                     usage_limit, usage_count, per_user_limit, store_id,
                     starts_at, expires_at, is_active, description)
OVERRIDING SYSTEM VALUE
VALUES
(1, 'WELCOME10',  'percentage', 10.00, 5000.00, 5000.00, 1000, 0, 1,
   NULL, now() - interval '1 day', now() + interval '30 days', TRUE,
   'خصم ترحيبي 10% لأول طلب (حد أقصى 5000 ر.ي)'),
(2, 'FREESHIP',   'fixed',      500.00, 0.00,    NULL,   NULL, 0, 999,
   NULL, now() - interval '7 days', now() + interval '90 days', TRUE,
   'شحن مجاني'),
(3, 'YEMEN25',    'percentage', 25.00, 10000.00, 10000.00, 500, 0, 1,
   NULL, now() - interval '30 days', now() + interval '60 days', TRUE,
   'عروض اليوم الوطني 25%'),
(4, 'SPICE20',    'percentage', 20.00, 3000.00, 3000.00, 200, 0, 2,
   1,    now() - interval '14 days', now() + interval '30 days', TRUE,
   'خصم 20% على بهارات اليمن')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('coupons','id'), GREATEST((SELECT MAX(id) FROM coupons), 1));

-- ---------------------------------------------------------------------
-- STORE_BALANCE — one per store
-- ---------------------------------------------------------------------
INSERT INTO store_balance (id, store_id, available, pending, currency)
OVERRIDING SYSTEM VALUE
VALUES
(1, 1, 250000.00, 35000.00, 'YER'),
(2, 2, 180000.00, 22000.00, 'YER'),
(3, 3, 320000.00, 45000.00, 'YER'),
(4, 4, 95000.00, 12000.00, 'YER'),
(5, 5, 150000.00, 28000.00, 'YER'),
(6, 6, 75000.00, 8000.00, 'YER'),
(7, 7, 420000.00, 65000.00, 'YER')
ON CONFLICT (store_id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('store_balance','id'), GREATEST((SELECT MAX(id) FROM store_balance), 1));

-- ---------------------------------------------------------------------
-- SUBSCRIPTIONS — one per store
-- ---------------------------------------------------------------------
INSERT INTO subscriptions (id, store_id, plan, status, started_at, expires_at,
                           amount, currency, auto_renew, features)
OVERRIDING SYSTEM VALUE
VALUES
(1, 1, 'pro',        'active',   now() - interval '90 days', now() + interval '275 days', 15000.00, 'YER', TRUE,
   '{"max_products": 500, "featured_slots": 5, "analytics": true}'::jsonb),
(2, 2, 'starter',    'active',   now() - interval '60 days', now() + interval '305 days', 5000.00,  'YER', TRUE,
   '{"max_products": 100, "featured_slots": 1, "analytics": false}'::jsonb),
(3, 3, 'enterprise', 'active',   now() - interval '180 days', now() + interval '185 days', 50000.00, 'YER', TRUE,
   '{"max_products": -1, "featured_slots": 20, "analytics": true, "priority_support": true}'::jsonb),
(4, 4, 'starter',    'active',   now() - interval '30 days', now() + interval '335 days', 5000.00,  'YER', FALSE,
   '{"max_products": 100, "featured_slots": 1, "analytics": false}'::jsonb),
(5, 5, 'free',       'active',   now() - interval '15 days', now() + interval '350 days', 0.00,     'YER', FALSE,
   '{"max_products": 20, "featured_slots": 0, "analytics": false}'::jsonb),
(6, 6, 'free',       'active',   now() - interval '10 days', now() + interval '355 days', 0.00,     'YER', FALSE,
   '{"max_products": 20, "featured_slots": 0, "analytics": false}'::jsonb),
(7, 7, 'pro',        'active',   now() - interval '180 days', now() + interval '185 days', 15000.00, 'YER', TRUE,
   '{"max_products": 500, "featured_slots": 5, "analytics": true}'::jsonb)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('subscriptions','id'), GREATEST((SELECT MAX(id) FROM subscriptions), 1));

-- ---------------------------------------------------------------------
-- ORDERS — 8 demo orders across the 3 customers
-- ---------------------------------------------------------------------
INSERT INTO orders (id, order_number, customer_id, store_id, status,
                    payment_method, payment_status, subtotal, shipping_cost,
                    discount, coupon_code, discount_amount, total, currency,
                    shipping_address, tracking_number, shipping_company,
                    estimated_delivery, delivered_at, cancelled_at,
                    timeline, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 'NOF-2026-0001', 2, 1, 'delivered', 'cod', 'paid',
    13000.00, 700.00, 0.00, NULL, 0.00, 13700.00, 'YER',
    '{"name":"أحمد المقتاري","phone":"+967712345671","city":"صنعاء","street":"شارع 30","building":"عمارة النور"}'::jsonb,
    'YE1234567890', 'Yemen Post', now() - interval '5 days', now() - interval '2 days', NULL,
    '[{"status":"pending","at":"2026-06-15T10:00:00Z","payment":"pending"},{"status":"delivered","at":"2026-06-18T14:30:00Z","payment":"paid"}]'::jsonb,
    now() - interval '7 days'),
(2, 'NOF-2026-0002', 2, 3, 'shipped',   'cod', 'pending',
    6500.00,  700.00, 0.00, NULL, 0.00, 7200.00, 'YER',
    '{"name":"أحمد المقتاري","phone":"+967712345671","city":"صنعاء","street":"شارع 30","building":"عمارة النور"}'::jsonb,
    'YE0987654321', 'Yemen Post', now() + interval '2 days', NULL, NULL,
    '[{"status":"pending","at":"2026-06-20T11:00:00Z","payment":"pending"}]'::jsonb,
    now() - interval '2 days'),
(3, 'NOF-2026-0003', 3, 2, 'processing','card', 'paid',
    25000.00, 1000.00, 0.00, NULL, 0.00, 26000.00, 'YER',
    '{"name":"سارة الحضرمي","phone":"+967712345672","city":"عدن","street":"شارع 10","building":"فيلا الزهراء"}'::jsonb,
    NULL, NULL, NULL, NULL, NULL,
    '[{"status":"pending","at":"2026-06-19T09:00:00Z","payment":"pending"},{"status":"confirmed","at":"2026-06-19T10:30:00Z","payment":"paid"}]'::jsonb,
    now() - interval '3 days'),
(4, 'NOF-2026-0004', 3, 7, 'pending',  'cod', 'pending',
    4500.00,  500.00, 500.00, 'FREESHIP', 500.00, 4500.00, 'YER',
    '{"name":"سارة الحضرمي","phone":"+967712345672","city":"عدن","street":"شارع 10","building":"فيلا الزهراء"}'::jsonb,
    NULL, NULL, NULL, NULL, NULL,
    '[{"status":"pending","at":"2026-06-21T08:00:00Z","payment":"pending"}]'::jsonb,
    now() - interval '1 day'),
(5, 'NOF-2026-0005', 4, 5, 'delivered','wallet', 'paid',
    85000.00, 1500.00, 8500.00, 'WELCOME10', 8500.00, 78000.00, 'YER',
    '{"name":"عمر العمري","phone":"+967712345673","city":"تعز","street":"شارع 15","building":"عمارة الأمل"}'::jsonb,
    'YE1122334455', 'Aramex', now() - interval '8 days', now() - interval '4 days', NULL,
    '[{"status":"pending","at":"2026-06-13T15:00:00Z","payment":"pending"},{"status":"delivered","at":"2026-06-16T12:00:00Z","payment":"paid"}]'::jsonb,
    now() - interval '10 days'),
(6, 'NOF-2026-0006', 2, 4, 'confirmed', 'bank_transfer', 'paid',
    15000.00, 1000.00, 0.00, NULL, 0.00, 16000.00, 'YER',
    '{"name":"أحمد المقتاري","phone":"+967712345671","city":"صنعاء","street":"شارع 30","building":"عمارة النور"}'::jsonb,
    NULL, NULL, NULL, NULL, NULL,
    '[{"status":"pending","at":"2026-06-21T07:00:00Z","payment":"pending"},{"status":"confirmed","at":"2026-06-21T08:00:00Z","payment":"paid"}]'::jsonb,
    now() - interval '12 hours'),
(7, 'NOF-2026-0007', 3, 1, 'cancelled','card', 'failed',
    8500.00, 700.00, 0.00, NULL, 0.00, 9200.00, 'YER',
    '{"name":"سارة الحضرمي","phone":"+967712345672","city":"عدن","street":"شارع 10","building":"فيلا الزهراء"}'::jsonb,
    NULL, NULL, NULL, NULL, now() - interval '6 hours',
    '[{"status":"pending","at":"2026-06-19T14:00:00Z","payment":"pending"},{"status":"cancelled","at":"2026-06-19T15:00:00Z","payment":"failed"}]'::jsonb,
    now() - interval '2 days'),
(8, 'NOF-2026-0008', 4, 7, 'delivered','cod', 'paid',
    7500.00, 500.00, 0.00, NULL, 0.00, 8000.00, 'YER',
    '{"name":"عمر العمري","phone":"+967712345673","city":"تعز","street":"شارع 15","building":"عمارة الأمل"}'::jsonb,
    'YE5566778899', 'Yemen Post', now() - interval '6 days', now() - interval '3 days', NULL,
    '[{"status":"pending","at":"2026-06-15T08:00:00Z","payment":"pending"},{"status":"delivered","at":"2026-06-17T11:00:00Z","payment":"paid"}]'::jsonb,
    now() - interval '8 days')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('orders','id'), GREATEST((SELECT MAX(id) FROM orders), 1));

-- ---------------------------------------------------------------------
-- ORDER_ITEMS — one to many per order (product_name is NOT NULL snapshot)
-- ---------------------------------------------------------------------
INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price, total_price)
OVERRIDING SYSTEM VALUE
VALUES
(1,  1, 1,  'عسل السدر اليمني الأصلي 500غ', 1, 8500.00, 8500.00),
(2,  1, 2,  'قهوة مخا اليمنية 250غ',         1, 4500.00, 4500.00),
(3,  2, 4,  'تمور مجدول فاخرة 1 كغ',         1, 6500.00, 6500.00),
(4,  3, 9,  'عود كمبودي فاخر 100غ',           1, 25000.00, 25000.00),
(5,  4, 18, 'قهوة عربية بالهيل 250غ',         1, 5500.00, 5500.00),
(6,  5, 12, 'هاتف ذكي 6.5 إنش',                1, 85000.00, 85000.00),
(7,  6, 7,  'طقم فضيات يمنية',                1, 15000.00, 15000.00),
(8,  7, 1,  'عسل السدر اليمني الأصلي 500غ', 1, 8500.00, 8500.00),
(9,  8, 19, 'قهوة تركية محمصة 500غ',          1, 7500.00, 7500.00)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('order_items','id'), GREATEST((SELECT MAX(id) FROM order_items), 1));

-- ---------------------------------------------------------------------
-- PAYMENTS — one row per paid/failed order
--   Order 2 is 'shipped' with payment_status='pending' → no payment row here
--   (COD on delivery). Order 7 is 'cancelled' with payment_status='failed'
--   → its payment row is the failed one.
-- ---------------------------------------------------------------------
INSERT INTO payments (id, order_id, user_id, method, status, amount, currency,
                      provider, provider_txn_id, paid_at, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 1, 2, 'cod',            'completed', 13700.00, 'YER', 'manual',  NULL,                now() - interval '2 days',  now() - interval '7 days'),
(2, 3, 3, 'card',           'completed', 26000.00, 'YER', 'stripe',  'pi_3MxxxDemo0001',  now() - interval '3 days',  now() - interval '3 days'),
(3, 5, 4, 'wallet',         'completed', 78000.00, 'YER', 'manual',  'WALLET-TXN-0001',   now() - interval '4 days',  now() - interval '10 days'),
(4, 6, 2, 'bank_transfer',  'completed', 16000.00, 'YER', 'manual',  'BANK-TXN-0001',    now() - interval '12 hours', now() - interval '12 hours'),
(5, 8, 4, 'cod',            'completed', 8000.00,  'YER', 'manual',  NULL,                now() - interval '3 days',  now() - interval '8 days'),
(6, 7, 3, 'card',           'failed',    9200.00,  'YER', 'stripe',  'pi_3MxxxDemo0002',  NULL,                        now() - interval '2 days')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('payments','id'), GREATEST((SELECT MAX(id) FROM payments), 1));

-- ---------------------------------------------------------------------
-- COUPON_USAGE — track which user redeemed which coupon
-- ---------------------------------------------------------------------
INSERT INTO coupon_usage (id, coupon_id, user_id, order_id, discount_amount)
OVERRIDING SYSTEM VALUE
VALUES
(1, 1, 4, 5, 5000.00),       -- capped by coupons.max_discount
(2, 2, 3, 4, 500.00)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('coupon_usage','id'), GREATEST((SELECT MAX(id) FROM coupon_usage), 1));
-- Bump coupons.usage_count
UPDATE coupons SET usage_count = (SELECT COUNT(*) FROM coupon_usage WHERE coupon_id = coupons.id);

-- ---------------------------------------------------------------------
-- REFUNDS — 1 demo refund (status='requested', awaiting admin review)
-- ---------------------------------------------------------------------
INSERT INTO refunds (id, order_id, payment_id, user_id, amount, reason, status,
                     admin_notes, resolved_by, resolved_at, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 7, NULL, 3, 9200.00, 'المنتج لم يصل في الوقت المحدد', 'requested',
   NULL, NULL, NULL, now() - interval '1 day')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('refunds','id'), GREATEST((SELECT MAX(id) FROM refunds), 1));

-- ---------------------------------------------------------------------
-- TRANSACTIONS — wallet ledger per store
-- ---------------------------------------------------------------------
INSERT INTO transactions (id, store_id, type, amount, balance_after, currency,
                           reference_type, reference_id, description, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 1, 'order',    10700.00, 10700.00, 'YER', 'order', 1, 'Order #NOF-2026-0001', now() - interval '7 days'),
(2, 1, 'fee',       -535.00, 10165.00, 'YER', 'order', 1, 'Platform fee 5%',    now() - interval '7 days'),
(3, 2, 'order',    26000.00, 26000.00, 'YER', 'order', 3, 'Order #NOF-2026-0003', now() - interval '3 days'),
(4, 2, 'fee',      -1300.00, 24700.00, 'YER', 'order', 3, 'Platform fee 5%',    now() - interval '3 days'),
(5, 3, 'order',     7200.00,  7200.00, 'YER', 'order', 2, 'Order #NOF-2026-0002', now() - interval '2 days'),
(6, 3, 'fee',       -360.00,  6840.00, 'YER', 'order', 2, 'Platform fee 5%',    now() - interval '2 days'),
(7, 7, 'order',     8000.00,  8000.00, 'YER', 'order', 8, 'Order #NOF-2026-0008', now() - interval '8 days'),
(8, 7, 'fee',       -400.00,  7600.00, 'YER', 'order', 8, 'Platform fee 5%',    now() - interval '8 days')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('transactions','id'), GREATEST((SELECT MAX(id) FROM transactions), 1));

-- ---------------------------------------------------------------------
-- REVIEWS — 10 verified reviews across products
-- ---------------------------------------------------------------------
INSERT INTO reviews (id, product_id, store_id, customer_id, order_id, rating,
                     title, comment, is_verified, is_visible, helpful_count,
                     merchant_reply, merchant_replied_at, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1,  1, 1, 2, 1, 5, 'عسل ممتاز',  'عسل أصلي بجودة عالية جداً، وصلني في الوقت المحدد وبتغليف ممتاز',
   TRUE, TRUE, 12, 'شكراً لاختيارك منتجاتنا، نتطلع لخدمتك مرة أخرى', now() - interval '1 day', now() - interval '2 days'),
(2,  1, 1, 3, 3, 5, 'أفضل عسل سدر',
   'جربت عسل السدر من عدة أماكن وهذا أفضلهم على الإطلاق',
   TRUE, TRUE, 8, NULL, NULL, now() - interval '1 day'),
(3,  2, 1, 2, 1, 4, 'قهوة جيدة',
   'قهوة مخا بنكهة قوية، مناسبة لعشاق القهوة',
   TRUE, TRUE, 5, NULL, NULL, now() - interval '1 day'),
(4,  4, 3, 3, NULL, 5, 'تمور فاخرة',
   'تمور مجدول درجة أولى، طعم رائع وحجم كبير',
   FALSE, TRUE, 3, NULL, NULL, now() - interval '3 days'),
(5,  5, 3, 2, NULL, 5, 'عجوة المدينة',
   'التمور العجوة طعم لا يُقاوم، شكراً لكم',
   FALSE, TRUE, 7, 'يسعدنا خدمتك', now() - interval '2 days', now() - interval '5 days'),
(6,  9, 2, 3, 3, 5, 'عود فاخر',
   'عود كمبودي بجودة عالية جداً، الرائحة مميزة',
   TRUE, TRUE, 4, NULL, NULL, now() - interval '1 day'),
(7,  10, 2, 2, NULL, 4, 'مسك جيد',
   'مسك نقي وطبيعي، يدوم طويلاً',
   FALSE, TRUE, 2, NULL, NULL, now() - interval '4 days'),
(8,  12, 5, 4, 5, 4, 'هاتف ممتاز',
   'أداء قوي وكاميرا رائعة، يستحق الشراء',
   TRUE, TRUE, 9, 'شكراً لثقتك بنا', now() - interval '3 days', now() - interval '4 days'),
(9,  14, 5, 2, NULL, 5, 'سماعات رائعة',
   'جودة صوت ممتازة وعمر بطارية طويل',
   FALSE, TRUE, 6, NULL, NULL, now() - interval '2 days'),
(10, 19, 7, 4, 8, 5, 'قهوة ممتازة',
   'قهوة تركية بنكهة أصيلة، تغليف ممتاز',
   TRUE, TRUE, 4, 'شكراً لتقييمك', now() - interval '2 days', now() - interval '3 days')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('reviews','id'), GREATEST((SELECT MAX(id) FROM reviews), 1));

-- ---------------------------------------------------------------------
-- STORE_FOLLOWERS — customers following stores
-- ---------------------------------------------------------------------
INSERT INTO store_followers (id, store_id, user_id, notify_new_products, notify_offers, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 1, 2, TRUE, TRUE,  now() - interval '30 days'),
(2, 1, 3, TRUE, TRUE,  now() - interval '15 days'),
(3, 2, 2, TRUE, FALSE, now() - interval '10 days'),
(4, 3, 3, TRUE, TRUE,  now() - interval '20 days'),
(5, 4, 4, FALSE, TRUE, now() - interval '5 days'),
(6, 5, 2, TRUE, TRUE,  now() - interval '7 days'),
(7, 7, 3, TRUE, TRUE,  now() - interval '12 days'),
(8, 7, 4, TRUE, FALSE, now() - interval '8 days')
ON CONFLICT (store_id, user_id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('store_followers','id'), GREATEST((SELECT MAX(id) FROM store_followers), 1));

-- ---------------------------------------------------------------------
-- WISHLIST — customers' saved products
-- ---------------------------------------------------------------------
INSERT INTO wishlist (id, user_id, product_id, notes, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 2, 5,  'هدية لشخص عزيز',            now() - interval '10 days'),
(2, 2, 11, NULL,                          now() - interval '8 days'),
(3, 2, 22, 'إذا توفر بسعر أقل',          now() - interval '5 days'),
(4, 3, 9,  NULL,                          now() - interval '12 days'),
(5, 3, 11, NULL,                          now() - interval '6 days'),
(6, 3, 14, NULL,                          now() - interval '4 days'),
(7, 4, 15, NULL,                          now() - interval '3 days'),
(8, 4, 12, 'انتظر عرض أفضل',              now() - interval '7 days')
ON CONFLICT (user_id, product_id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('wishlist','id'), GREATEST((SELECT MAX(id) FROM wishlist), 1));

-- ---------------------------------------------------------------------
-- CART_ITEMS — 1 active cart per customer
-- ---------------------------------------------------------------------
INSERT INTO cart_items (id, user_id, product_id, quantity, created_at, updated_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 2, 3,  2, now() - interval '1 day', now() - interval '1 day'),
(2, 3, 14, 1, now() - interval '2 days', now() - interval '2 days'),
(3, 4, 8,  1, now() - interval '3 hours', now() - interval '3 hours')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('cart_items','id'), GREATEST((SELECT MAX(id) FROM cart_items), 1));

-- ---------------------------------------------------------------------
-- MESSAGES — customer ↔ merchant chat
-- ---------------------------------------------------------------------
INSERT INTO messages (id, sender_id, receiver_id, store_id, body, is_read, read_at, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 2, 5, 1, 'مرحباً، هل المنتج متوفر؟',  TRUE,  now() - interval '2 hours',  now() - interval '3 hours'),
(2, 5, 2, 1, 'نعم متوفر، يمكنني تأكيد الطلب', TRUE, now() - interval '1 hour',   now() - interval '2 hours'),
(3, 3, 6, 3, 'متى يصل الطلب؟',              TRUE,  now() - interval '30 minutes', now() - interval '1 hour'),
(4, 6, 3, 3, 'خلال 24 ساعة بإذن الله',     FALSE, NULL,                          now() - interval '15 minutes')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('messages','id'), GREATEST((SELECT MAX(id) FROM messages), 1));

-- ---------------------------------------------------------------------
-- NOTIFICATIONS — system + transactional
-- ---------------------------------------------------------------------
INSERT INTO notifications (id, user_id, type, title, body, data, is_read, read_at, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 2, 'order',    'تم استلام طلبك',        'طلبك #NOF-2026-0001 قيد المعالجة',
   '{"order_id":1,"order_number":"NOF-2026-0001"}'::jsonb, FALSE, NULL,                       now() - interval '7 days'),
(2, 2, 'order',    'تم شحن طلبك',           'طلبك #NOF-2026-0001 في الطريق إليك',
   '{"order_id":1,"tracking":"YE1234567890"}'::jsonb, TRUE,  now() - interval '3 days',      now() - interval '4 days'),
(3, 2, 'order',    'تم تسليم طلبك',         'تم تسليم طلبك بنجاح',
   '{"order_id":1}'::jsonb,                                                  FALSE, NULL,                       now() - interval '2 days'),
(4, 3, 'order',    'تم استلام طلبك',        'طلبك #NOF-2026-0003',
   '{"order_id":3}'::jsonb,                                                  TRUE,  now() - interval '12 hours',    now() - interval '3 days'),
(5, 3, 'promo',    'عرض خاص!',             'خصم 25% على المنتجات المختارة',
   '{"coupon_code":"YEMEN25"}'::jsonb,                                       FALSE, NULL,                       now() - interval '1 day'),
(6, 4, 'order',    'تم تسليم طلبك',         'تم تسليم طلبك #NOF-2026-0005',
   '{"order_id":5}'::jsonb,                                                  TRUE,  now() - interval '3 days',      now() - interval '4 days'),
(7, 3, 'refund',   'تم معالجة استرجاعك',     'تم رد مبلغ 9200 ر.ي',
   '{"refund_id":1}'::jsonb,                                                 FALSE, NULL,                       now() - interval '1 day'),
(8, 4, 'system',   'تحديث النظام',          'تم تحديث نظام المدفوعات',
   '{}'::jsonb,                                                              TRUE,  now() - interval '2 days',      now() - interval '3 days')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('notifications','id'), GREATEST((SELECT MAX(id) FROM notifications), 1));

-- ---------------------------------------------------------------------
-- DISPUTES — 1 open dispute
-- ---------------------------------------------------------------------
INSERT INTO disputes (id, order_id, customer_id, store_id, type, status, priority,
                     subject, description, evidence, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 7, 3, 2, 'not_received', 'investigating', 'high',
   'لم يصل الطلب', 'الطلب لم يصل حتى الآن رغم مرور 48 ساعة',
   '[]'::jsonb, now() - interval '1 day')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('disputes','id'), GREATEST((SELECT MAX(id) FROM disputes), 1));

-- ---------------------------------------------------------------------
-- ADMIN_AUDIT_LOG — sample admin actions
-- ---------------------------------------------------------------------
INSERT INTO admin_audit_log (id, user_id, action, entity_type, entity_id, old_values, new_values, created_at)
OVERRIDING SYSTEM VALUE
VALUES
(1, 1, 'APPROVE',  'store',     '7',
   '{"is_verified":false,"trust_level":"verified"}'::jsonb,
   '{"is_verified":true,"trust_level":"diamond"}'::jsonb,
   now() - interval '30 days'),
(2, 1, 'CREATE',   'coupon',    '1', NULL,
   '{"code":"WELCOME10","type":"percentage","value":10}'::jsonb,
   now() - interval '7 days'),
(3, 1, 'RESOLVE',  'refund',    '1', NULL,
   '{"status":"processed","admin_notes":"تم رد المبلغ"}'::jsonb,
   now() - interval '1 day'),
(4, 1, 'VERIFY',   'merchant',  '5',
   '{"kyc_status":"pending"}'::jsonb,
   '{"kyc_status":"verified"}'::jsonb,
   now() - interval '60 days'),
(5, 1, 'BAN',      'user',      '4',
   '{"status":"active"}'::jsonb,
   '{"status":"banned","reason":"fraud"}'::jsonb,
   now() - interval '15 days')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('admin_audit_log','id'), GREATEST((SELECT MAX(id) FROM admin_audit_log), 1));

COMMIT;
