/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Email + password login. Sets the `noufex_auth` HttpOnly cookie on success. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginEnvelope"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Rate-limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Full category tree with product counts. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category tree */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoriesListEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness probe — returns 200 while the process is running. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Prometheus exposition (text/plain version 0.0.4). No auth — bind to internal network only. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics in Prometheus format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description This document. OpenAPI 3.1, JSON. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List products with filters and pagination. */
        get: {
            parameters: {
                query?: {
                    /** @description Category slug */
                    category?: string;
                    limit?: components["schemas"]["LimitParam"];
                    maxPrice?: number | null;
                    minPrice?: number | null;
                    offset?: components["schemas"]["OffsetParam"];
                    /** @description Full-text search term (LIKE-based in dev, ES in prod) */
                    search?: string;
                    sort?: PathsApiProductsGetParametersQuerySort;
                    store?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Catalog page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductsListEnvelope"];
                    };
                };
                /** @description Invalid filter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Single product + its store + reviews + images. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Products with an active deal_discount > 0. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Up to 10 deal products */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductHitListEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Curated featured products (homepage hero). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Up to 10 featured products */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductHitListEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Readiness probe — reports status of PG / Redis / RabbitMQ / Elasticsearch. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All checks passed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            checks: {
                                [key: string]: {
                                    detail?: string;
                                    ms: number;
                                    ok: boolean;
                                };
                            };
                            /** @enum {string} */
                            status: PathsApiReadyGetResponses200ContentApplicationJsonStatus;
                        };
                    };
                };
                /** @description At least one check failed */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: PathsApiReadyGetResponses503ContentApplicationJsonStatus;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Full-text product search. Elasticsearch-first with PostgreSQL FTS fallback. */
        get: {
            parameters: {
                query: {
                    category?: string;
                    limit?: components["schemas"]["LimitParam"];
                    maxPrice?: number | null;
                    minPrice?: number | null;
                    offset?: components["schemas"]["OffsetParam"];
                    q: string;
                    sort?: PathsApiSearchGetParametersQuerySort;
                    store?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search hits + facets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchEnvelope"];
                    };
                };
                /** @description Missing query parameter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description All search backends unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Autocomplete suggestions for the search box. Backs the typeahead. */
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Top 10 suggestions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuggestEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Homepage stats: counts, featured, deals. (Redis-cached 30s.) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Homepage data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HomeStatsEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthUser: {
            /** Format: email */
            email: string;
            full_name: string;
            id: number;
            /** @enum {string} */
            role: AuthUserRole;
        };
        CategoriesListEnvelope: {
            data: components["schemas"]["CategoriesListResponse"];
            message?: string;
            request_id?: string;
            /** @enum {boolean} */
            success: true;
        };
        CategoriesListResponse: {
            categories: components["schemas"]["CategoryNode"][];
        };
        CategoryNode: {
            id: number;
            name_ar: string;
            name_en?: string | null;
            name_zh?: string | null;
            parent_id?: number | null;
            product_count?: number;
            slug: string;
        };
        ErrorEnvelope: {
            /** @description Stable machine-readable error code (e.g. `NOT_FOUND`) */
            code?: string;
            details?: unknown;
            /** @description Human-readable error message */
            error: string;
            /** @description Server-generated correlation id */
            request_id?: string;
            /** @enum {boolean} */
            success: false;
        };
        HomeStats: {
            counts: {
                orders: number;
                products: number;
                stores: number;
                users: number;
            };
            deals: components["schemas"]["ProductHit"][];
            featured: components["schemas"]["ProductHit"][];
        };
        HomeStatsEnvelope: {
            data: components["schemas"]["HomeStats"];
            message?: string;
            request_id?: string;
            /** @enum {boolean} */
            success: true;
        };
        /** @default 20 */
        LimitParam: number;
        LoginEnvelope: {
            data: components["schemas"]["LoginResponse"];
            message?: string;
            request_id?: string;
            /** @enum {boolean} */
            success: true;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            /** @description Bearer token (mobile clients only) */
            token?: string;
            user: components["schemas"]["AuthUser"];
        };
        /** @default 0 */
        OffsetParam: number | null;
        ProductHit: {
            category_id: number;
            currency: string;
            deal_discount?: number;
            id: number;
            main_image?: string | null;
            name_ar: string;
            name_en?: string | null;
            name_zh?: string | null;
            price: number;
            rating?: number;
            sold_count?: number;
            store_id: number;
            store_name: string;
        };
        ProductHitListEnvelope: {
            data: components["schemas"]["ProductHit"][];
            message?: string;
            request_id?: string;
            /** @enum {boolean} */
            success: true;
        };
        ProductsListEnvelope: {
            data: components["schemas"]["ProductsListResponse"];
            message?: string;
            request_id?: string;
            /** @enum {boolean} */
            success: true;
        };
        ProductsListResponse: {
            limit: number;
            offset: number;
            products: components["schemas"]["ProductHit"][];
            total: number;
        };
        SearchEnvelope: {
            data: components["schemas"]["SearchResponse"];
            message?: string;
            request_id?: string;
            /** @enum {boolean} */
            success: true;
        };
        SearchResponse: {
            duration_ms: number;
            facets?: {
                categories: {
                    count: number;
                    key: string;
                }[];
                priceRanges: {
                    count: number;
                    key: string;
                }[];
            };
            limit: number;
            offset: number;
            products: components["schemas"]["ProductHit"][];
            query: string;
            /** @enum {string} */
            source: SearchResponseSource;
            total: number;
        };
        SuggestEnvelope: {
            data: components["schemas"]["SuggestResponse"];
            message?: string;
            request_id?: string;
            /** @enum {boolean} */
            success: true;
        };
        SuggestResponse: {
            suggestions: {
                score: number;
                text: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum PathsApiProductsGetParametersQuerySort {
    relevance = "relevance",
    price_asc = "price_asc",
    price_desc = "price_desc",
    newest = "newest",
    popular = "popular"
}
export enum PathsApiReadyGetResponses200ContentApplicationJsonStatus {
    ready = "ready"
}
export enum PathsApiReadyGetResponses503ContentApplicationJsonStatus {
    degraded = "degraded"
}
export enum PathsApiSearchGetParametersQuerySort {
    relevance = "relevance",
    price_asc = "price_asc",
    price_desc = "price_desc",
    newest = "newest",
    best_selling = "best_selling"
}
export enum AuthUserRole {
    customer = "customer",
    merchant = "merchant",
    admin = "admin"
}
export enum SearchResponseSource {
    elasticsearch = "elasticsearch",
    postgresql = "postgresql"
}
export type operations = Record<string, never>;
